### ISSUE TITLE
Your code is too long..

### ISSUE THREAD

**Issue by msizi007** [TheJeebo/Hydra#41]
I understand you may be experiencing pygame which is a good thing. I may try to help by creating a branch that will simplify your code especially the Hydra class. You need to consider using sprites in the future. Video to sprites tutotial => https://www.youtube.com/watch?v=hDu8mcAlY4E

I would appreciate your response!

**Comment by TheJeebo** [comment]
The readability is fine for being this long, I'm not worried about it.

Sprites are not in scope for this project. It was made to replicate arcade games like Asteroids that use simple geometry.

I'll close this issue, but you're more than welcome to make a branch. I'm done with this project.
